### ISSUE TITLE
How  to create the pair count file ?

### ISSUE THREAD

**Issue by Saltychtao** [mandarjoshi90/pair2vec#2]
Dear authors, I want to pretrain my own word pair representations on a wiki corpus. By the instruction I need to run `python -m embedding.preprocess` to preprocess my corpus. I notice that `preprocess.py` requires an argument called `pair_count_file`, however, I cannot find any code on  counting the word pair statistics.  Would you tell me how to create this file ?

**Comment by mandarjoshi90** [comment]
Thanks! I just added `embeddings.cooccurance` which should generate the file for you..
